services:
  data-consumer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    user: vscode
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    env_file:
      - ../Infrastructure/.env
    environment:
      POSTGRES_HOST: timescale
      NATS_HOST: nats
    depends_on:
      timescale:
        condition: service_healthy
      nats:
        condition: service_started

include:
  - path: ../Infrastructure/docker-compose.yml
